### ISSUE TITLE
UI Enhancement: Better Hovers on Size and Time

### ISSUE THREAD

**Issue by apoapostolov** [kregfile/kregfile#67]
Hover over size: could use , separators for thousands, millions, etc.

Hover over date: could show relative time compared to now (i.e. "7 minutes ago")

**Comment by RealDolos** [comment]
Where in the UI do you even see large numbers? Filesizes are already "prettified" from bytes to whatever larger unit fits better. If they are not for you, then that's a bug warranting investigation.

As for the dates and/or timestamps, I'd rather not do relative times. Especially not for things that are always visible like the chat timestamps because then you get very-variable sized values AND worse have to keep updating them because time progresses and what was "7 mins ago" a minute ago is now "8 mins ago".

For the file tooltip, I could see some value in showing a relative time along with the timestamp for the "Uploaded" field.

**Comment by apoapostolov** [comment]
@RealDolos large numbers are on hover, and can be prettified with separating comma

![image](https://user-images.githubusercontent.com/4083812/127125818-eadc4ea5-80bd-4da9-935f-929acf9b3c32.png)

**Comment by RealDolos** [comment]
That's one of @voroneril's custom additions so far. See #66 

Anything else?

**Comment by apoapostolov** [comment]
Thank you, this is very nice.
